"""
Setup script to configure OpenRouter model selection
Reads API key from .env file (keeps it secure!)
"""

import os
from dotenv import load_dotenv

# Load existing .env if it exists
load_dotenv()

# Get API key from environment or prompt user
API_KEY = os.getenv("OPENROUTER_API_KEY")

if not API_KEY:
    print("⚠️  No API key found!")
    print()
    API_KEY = input("Enter your OpenRouter API key: ").strip()
    if not API_KEY:
        print("❌ API key is required. Exiting.")
        exit(1)

# Available FREE vision models
FREE_MODELS = {
    "1": {
        "name": "Google Gemini 2.0 Flash",
        "id": "google/gemini-2.0-flash-exp:free",
        "speed": "⚡⚡⚡ Fast (2-3s)",
        "accuracy": "⭐⭐⭐⭐⭐ Excellent",
        "best_for": "Complex graphs, detailed diagrams",
        "recommended": True
    },
    "2": {
        "name": "NVIDIA Nemotron Nano",
        "id": "nvidia/nemotron-nano-12b-v2-vl:free",
        "speed": "⚡⚡⚡⚡ Very Fast (1-2s)",
        "accuracy": "⭐⭐⭐⭐ Very Good",
        "best_for": "Simple diagrams, quick extraction"
    },
    "3": {
        "name": "Meta Llama 3.2 Vision",
        "id": "meta-llama/llama-3.2-11b-vision-instruct:free",
        "speed": "⚡⚡ Medium (3-5s)",
        "accuracy": "⭐⭐⭐⭐⭐ Excellent",
        "best_for": "Complex graphs, high accuracy needed"
    },
    "4": {
        "name": "Qwen 2 VL",
        "id": "qwen/qwen-2-vl-7b-instruct:free",
        "speed": "⚡⚡ Medium (3-4s)",
        "accuracy": "⭐⭐⭐⭐ Very Good",
        "best_for": "Handwritten graphs, varied styles"
    }
}

def create_env_file(model_id):
    """Create .env file with API key and selected model"""
    env_content = f"""# OpenRouter API Configuration
# Auto-generated by setup_api_key.py

OPENROUTER_API_KEY={API_KEY}
OPENROUTER_MODEL={model_id}

# To change model, run: python setup_api_key.py
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"✅ Created .env file with model: {model_id}")

def main():
    print("="*70)
    print("🚀 OpenRouter API Setup - Free Vision Models")
    print("="*70)
    print()
    print("Choose your AI model for DAG extraction:")
    print()
    
    for key, model in FREE_MODELS.items():
        recommended = " ⭐ RECOMMENDED" if model.get("recommended") else ""
        print(f"{key}. {model['name']}{recommended}")
        print(f"   ID: {model['id']}")
        print(f"   Speed: {model['speed']}")
        print(f"   Accuracy: {model['accuracy']}")
        print(f"   Best for: {model['best_for']}")
        print()
    
    print("="*70)
    
    # Get user choice
    while True:
        choice = input("Enter your choice (1-4) [default: 1]: ").strip() or "1"
        
        if choice in FREE_MODELS:
            selected = FREE_MODELS[choice]
            print()
            print(f"✅ Selected: {selected['name']}")
            print(f"   Model ID: {selected['id']}")
            
            # Create .env file
            create_env_file(selected['id'])
            
            print()
            print("="*70)
            print("🎉 Setup Complete!")
            print("="*70)
            print()
            print("Next steps:")
            print("1. Start backend: python main.py")
            print("2. Open app: http://localhost:5173")
            print("3. Upload a DAG image")
            print("4. Watch it extract automatically! ✨")
            print()
            print("To change model later, run: python setup_api_key.py")
            print()
            break
        else:
            print("❌ Invalid choice. Please enter 1-4.")

if __name__ == "__main__":
    main()

